### ISSUE TITLE
arranger api doesn't resolve hits that have null values

### ISSUE THREAD

**Issue by philloooo** [overture-stack/arranger#317]
So I am trying arranger with the hcmi instance. I loaded some dummy data and found that if a document has a null value for a field, the whole table in the portal disappear because:
```
graphql server running at /test/graphql
TypeError: Cannot read property 'constructor' of null
    at /Users/phillis/Documents/work/hcmi-portal/api/node_modules/@arranger/mapping-utils/dist/resolveHits.js:58:56
    at Array.reduce (<anonymous>)
    at resolveNested (/Users/phillis/Documents/work/hcmi-portal/api/node_modules/@arranger/mapping-utils/dist/resolveHits.js:38:31)
    at /Users/phillis/Documents/work/hcmi-portal/api/node_modules/@arranger/mapping-utils/dist/resolveHits.js:139:38
    at Array.map (<anonymous>)
    at _callee$ (/Users/phillis/Documents/work/hcmi-portal/api/node_modules/@arranger/mapping-utils/dist/resolveHits.js:137:35)
    at tryCatch (/Users/phillis/Documents/work/hcmi-portal/api/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/phillis/Documents/work/hcmi-portal/api/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/phillis/Documents/work/hcmi-portal/api/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/phillis/Documents/work/hcmi-portal/api/node_modules/@arranger/mapping-utils/dist/resolveHits.js:16:221)
```

BTW this is a great product! We might want to use it for some of our use cases and would like to learn and contribute too

**Comment by cy** [comment]
ran into a similar issue, might have fixed it https://github.com/overture-stack/arranger/pull/342/files#diff-99d736c38bd377bc54480142bbe784e5R27 :slightly_smiling_face:

**Comment by rosibaj** [comment]
@hlminh2000 is this still an issue that is happening?
